/*					TASK#03
Write a C++ program to find the size of fundamentals data types:
				(((STARTING OF PROGRAM))) */

#include"iostream"
using namespace std;
int main()
{
	cout<<"Size Of Fundamental Data Types"<<endl;
	cout<<"Size of int: "<<sizeof(int)<<" bytes"<<endl;
	cout<<"Size of Long: "<<sizeof(long)<<" bytes"<<endl;
	cout<<"Size of short: "<<sizeof(short)<<" bytes"<<endl;
	cout<<"Size of char: "<<sizeof(char)<<" byte"<<endl;
	cout<<"Size of bool: "<<sizeof(bool)<<" byte"<<endl;
	return 0; }				



